Fabric:
  user: admin
  secret: adminpw
  org: sampleorg
  channel: wheelsets
  connectionProfile: /home/user/config-dev-2orgs.yaml

Db:
  host: localhost
  port: 27017
  dbuser: dbuser
  dbsecret: dbpass
  dbname: blocks
  collection: txs

GRPCServer:
  host: localhost
  port: 6000
