Fabric:
  user: admin
  secret: adminpw
  org: rzd
  channel: wheelsets
  connectionProfile: /home/vadim/wheelsets-fabric/wheelsets-core/app/blockchain/fabric/config-dev-2orgs.yaml

Db:
  host: localhost
  port: 27017
  dbuser: postgres
  dbsecret: 1
  dbname: blocks
  collection: txs

GRPCServer:
  host: localhost
  port: 6000