// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: fabex.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type RequestRange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Startblock int64 `protobuf:"varint,1,opt,name=startblock,proto3" json:"startblock,omitempty"`
	Endblock   int64 `protobuf:"varint,2,opt,name=endblock,proto3" json:"endblock,omitempty"`
}

func (x *RequestRange) Reset() {
	*x = RequestRange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fabex_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestRange) ProtoMessage() {}

func (x *RequestRange) ProtoReflect() protoreflect.Message {
	mi := &file_fabex_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestRange.ProtoReflect.Descriptor instead.
func (*RequestRange) Descriptor() ([]byte, []int) {
	return file_fabex_proto_rawDescGZIP(), []int{0}
}

func (x *RequestRange) GetStartblock() int64 {
	if x != nil {
		return x.Startblock
	}
	return 0
}

func (x *RequestRange) GetEndblock() int64 {
	if x != nil {
		return x.Endblock
	}
	return 0
}

type Entry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Channelid      string `protobuf:"bytes,1,opt,name=channelid,proto3" json:"channelid,omitempty"`
	Txid           string `protobuf:"bytes,2,opt,name=txid,proto3" json:"txid,omitempty"`
	Hash           string `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	Previoushash   string `protobuf:"bytes,4,opt,name=previoushash,proto3" json:"previoushash,omitempty"`
	Blocknum       uint64 `protobuf:"varint,5,opt,name=blocknum,proto3" json:"blocknum,omitempty"`
	Payload        []byte `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	Time           int64  `protobuf:"varint,7,opt,name=time,proto3" json:"time,omitempty"`
	Validationcode int32  `protobuf:"varint,8,opt,name=validationcode,proto3" json:"validationcode,omitempty"`
}

func (x *Entry) Reset() {
	*x = Entry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fabex_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_fabex_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_fabex_proto_rawDescGZIP(), []int{1}
}

func (x *Entry) GetChannelid() string {
	if x != nil {
		return x.Channelid
	}
	return ""
}

func (x *Entry) GetTxid() string {
	if x != nil {
		return x.Txid
	}
	return ""
}

func (x *Entry) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *Entry) GetPrevioushash() string {
	if x != nil {
		return x.Previoushash
	}
	return ""
}

func (x *Entry) GetBlocknum() uint64 {
	if x != nil {
		return x.Blocknum
	}
	return 0
}

func (x *Entry) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Entry) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *Entry) GetValidationcode() int32 {
	if x != nil {
		return x.Validationcode
	}
	return 0
}

var File_fabex_proto protoreflect.FileDescriptor

var file_fabex_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x66, 0x61, 0x62, 0x65, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x66,
	0x61, 0x62, 0x65, 0x78, 0x22, 0x4a, 0x0a, 0x0c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52,
	0x61, 0x6e, 0x67, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x62, 0x6c, 0x6f,
	0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x62,
	0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x62, 0x6c, 0x6f, 0x63, 0x6b,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x65, 0x6e, 0x64, 0x62, 0x6c, 0x6f, 0x63, 0x6b,
	0x22, 0xe3, 0x01, 0x0a, 0x05, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x78, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x78, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x68, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68,
	0x12, 0x22, 0x0a, 0x0c, 0x70, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x68, 0x61, 0x73, 0x68,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73,
	0x68, 0x61, 0x73, 0x68, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x6e, 0x75, 0x6d,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x6e, 0x75, 0x6d,
	0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x26,
	0x0a, 0x0e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x32, 0x5d, 0x0a, 0x05, 0x46, 0x61, 0x62, 0x65, 0x78, 0x12,
	0x23, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x0c, 0x2e, 0x66, 0x61, 0x62, 0x65, 0x78, 0x2e, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x1a, 0x0c, 0x2e, 0x66, 0x61, 0x62, 0x65, 0x78, 0x2e, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x30, 0x01, 0x12, 0x2f, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x52, 0x61, 0x6e, 0x67, 0x65,
	0x12, 0x13, 0x2e, 0x66, 0x61, 0x62, 0x65, 0x78, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x52, 0x61, 0x6e, 0x67, 0x65, 0x1a, 0x0c, 0x2e, 0x66, 0x61, 0x62, 0x65, 0x78, 0x2e, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x30, 0x01, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x79, 0x70, 0x65, 0x72, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x2d,
	0x6c, 0x61, 0x62, 0x73, 0x2f, 0x66, 0x61, 0x62, 0x65, 0x78, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_fabex_proto_rawDescOnce sync.Once
	file_fabex_proto_rawDescData = file_fabex_proto_rawDesc
)

func file_fabex_proto_rawDescGZIP() []byte {
	file_fabex_proto_rawDescOnce.Do(func() {
		file_fabex_proto_rawDescData = protoimpl.X.CompressGZIP(file_fabex_proto_rawDescData)
	})
	return file_fabex_proto_rawDescData
}

var file_fabex_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_fabex_proto_goTypes = []interface{}{
	(*RequestRange)(nil), // 0: fabex.RequestRange
	(*Entry)(nil),        // 1: fabex.Entry
}
var file_fabex_proto_depIdxs = []int32{
	1, // 0: fabex.Fabex.Get:input_type -> fabex.Entry
	0, // 1: fabex.Fabex.GetRange:input_type -> fabex.RequestRange
	1, // 2: fabex.Fabex.Get:output_type -> fabex.Entry
	1, // 3: fabex.Fabex.GetRange:output_type -> fabex.Entry
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_fabex_proto_init() }
func file_fabex_proto_init() {
	if File_fabex_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_fabex_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestRange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fabex_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Entry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_fabex_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fabex_proto_goTypes,
		DependencyIndexes: file_fabex_proto_depIdxs,
		MessageInfos:      file_fabex_proto_msgTypes,
	}.Build()
	File_fabex_proto = out.File
	file_fabex_proto_rawDesc = nil
	file_fabex_proto_goTypes = nil
	file_fabex_proto_depIdxs = nil
}
