// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fabex.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RequestRange struct {
	Startblock           int64    `protobuf:"varint,1,opt,name=startblock,proto3" json:"startblock,omitempty"`
	Endblock             int64    `protobuf:"varint,2,opt,name=endblock,proto3" json:"endblock,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestRange) Reset()         { *m = RequestRange{} }
func (m *RequestRange) String() string { return proto.CompactTextString(m) }
func (*RequestRange) ProtoMessage()    {}
func (*RequestRange) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7d7206373264ff4, []int{0}
}

func (m *RequestRange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestRange.Unmarshal(m, b)
}
func (m *RequestRange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestRange.Marshal(b, m, deterministic)
}
func (m *RequestRange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestRange.Merge(m, src)
}
func (m *RequestRange) XXX_Size() int {
	return xxx_messageInfo_RequestRange.Size(m)
}
func (m *RequestRange) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestRange.DiscardUnknown(m)
}

var xxx_messageInfo_RequestRange proto.InternalMessageInfo

func (m *RequestRange) GetStartblock() int64 {
	if m != nil {
		return m.Startblock
	}
	return 0
}

func (m *RequestRange) GetEndblock() int64 {
	if m != nil {
		return m.Endblock
	}
	return 0
}

type Entry struct {
	Channelid            string   `protobuf:"bytes,1,opt,name=channelid,proto3" json:"channelid,omitempty"`
	Txid                 string   `protobuf:"bytes,2,opt,name=txid,proto3" json:"txid,omitempty"`
	Hash                 string   `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	Previoushash         string   `protobuf:"bytes,4,opt,name=previoushash,proto3" json:"previoushash,omitempty"`
	Blocknum             uint64   `protobuf:"varint,5,opt,name=blocknum,proto3" json:"blocknum,omitempty"`
	Payload              string   `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	Time                 int64    `protobuf:"varint,7,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Entry) Reset()         { *m = Entry{} }
func (m *Entry) String() string { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()    {}
func (*Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7d7206373264ff4, []int{1}
}

func (m *Entry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entry.Unmarshal(m, b)
}
func (m *Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entry.Marshal(b, m, deterministic)
}
func (m *Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entry.Merge(m, src)
}
func (m *Entry) XXX_Size() int {
	return xxx_messageInfo_Entry.Size(m)
}
func (m *Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_Entry.DiscardUnknown(m)
}

var xxx_messageInfo_Entry proto.InternalMessageInfo

func (m *Entry) GetChannelid() string {
	if m != nil {
		return m.Channelid
	}
	return ""
}

func (m *Entry) GetTxid() string {
	if m != nil {
		return m.Txid
	}
	return ""
}

func (m *Entry) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *Entry) GetPrevioushash() string {
	if m != nil {
		return m.Previoushash
	}
	return ""
}

func (m *Entry) GetBlocknum() uint64 {
	if m != nil {
		return m.Blocknum
	}
	return 0
}

func (m *Entry) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

func (m *Entry) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func init() {
	proto.RegisterType((*RequestRange)(nil), "fabex.RequestRange")
	proto.RegisterType((*Entry)(nil), "fabex.Entry")
}

func init() { proto.RegisterFile("fabex.proto", fileDescriptor_d7d7206373264ff4) }

var fileDescriptor_d7d7206373264ff4 = []byte{
	// 279 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x51, 0xcd, 0x4e, 0x83, 0x40,
	0x10, 0x0e, 0x02, 0x6d, 0x19, 0x39, 0xad, 0x97, 0x4d, 0x63, 0x4c, 0x83, 0x07, 0xeb, 0x41, 0x30,
	0xfa, 0x06, 0x26, 0xda, 0xc4, 0xe3, 0x1e, 0x4d, 0x3c, 0x2c, 0x30, 0x02, 0x11, 0x76, 0x71, 0x59,
	0x4c, 0x79, 0x36, 0x5f, 0xce, 0x30, 0xd4, 0xda, 0xf6, 0xc4, 0xf7, 0xc3, 0xb7, 0x3b, 0xf3, 0x2d,
	0x9c, 0x7f, 0xc8, 0x14, 0xb7, 0x71, 0x6b, 0xb4, 0xd5, 0xcc, 0x27, 0x12, 0xbd, 0x42, 0x28, 0xf0,
	0xab, 0xc7, 0xce, 0x0a, 0xa9, 0x0a, 0x64, 0x57, 0x00, 0x9d, 0x95, 0xc6, 0xa6, 0xb5, 0xce, 0x3e,
	0xb9, 0xb3, 0x72, 0xd6, 0xae, 0x38, 0x50, 0xd8, 0x12, 0x16, 0xa8, 0xf2, 0xc9, 0x3d, 0x23, 0x77,
	0xcf, 0xa3, 0x1f, 0x07, 0xfc, 0x67, 0x65, 0xcd, 0xc0, 0x2e, 0x21, 0xc8, 0x4a, 0xa9, 0x14, 0xd6,
	0x55, 0x4e, 0x87, 0x04, 0xe2, 0x5f, 0x60, 0x0c, 0x3c, 0xbb, 0xad, 0x72, 0xca, 0x07, 0x82, 0xf0,
	0xa8, 0x95, 0xb2, 0x2b, 0xb9, 0x3b, 0x69, 0x23, 0x66, 0x11, 0x84, 0xad, 0xc1, 0xef, 0x4a, 0xf7,
	0x1d, 0x79, 0x1e, 0x79, 0x47, 0xda, 0x38, 0x0f, 0x5d, 0xae, 0xfa, 0x86, 0xfb, 0x2b, 0x67, 0xed,
	0x89, 0x3d, 0x67, 0x1c, 0xe6, 0xad, 0x1c, 0x6a, 0x2d, 0x73, 0x3e, 0xa3, 0xe8, 0x1f, 0xa5, 0x09,
	0xaa, 0x06, 0xf9, 0x9c, 0x36, 0x20, 0xfc, 0xf0, 0x0e, 0xfe, 0xcb, 0x58, 0x09, 0xbb, 0x06, 0x77,
	0x83, 0x96, 0x85, 0xf1, 0x54, 0x17, 0x6d, 0xb4, 0x3c, 0x62, 0xf7, 0x0e, 0x4b, 0x60, 0xb1, 0xc1,
	0x5d, 0x67, 0x17, 0x3b, 0xef, 0xb0, 0xc8, 0xd3, 0xc0, 0xd3, 0xed, 0xdb, 0x4d, 0x51, 0xd9, 0xb2,
	0x4f, 0xe3, 0x4c, 0x37, 0x49, 0x39, 0xb4, 0x68, 0x6a, 0xcc, 0x0b, 0x34, 0x77, 0xb5, 0x4c, 0xbb,
	0x84, 0x7e, 0x4e, 0xe8, 0x69, 0xd2, 0x19, 0x7d, 0x1e, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x8b,
	0xe9, 0x02, 0x6f, 0xb0, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FabexClient is the client API for Fabex service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FabexClient interface {
	Get(ctx context.Context, in *Entry, opts ...grpc.CallOption) (Fabex_GetClient, error)
	GetRange(ctx context.Context, in *RequestRange, opts ...grpc.CallOption) (Fabex_GetRangeClient, error)
}

type fabexClient struct {
	cc *grpc.ClientConn
}

func NewFabexClient(cc *grpc.ClientConn) FabexClient {
	return &fabexClient{cc}
}

func (c *fabexClient) Get(ctx context.Context, in *Entry, opts ...grpc.CallOption) (Fabex_GetClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Fabex_serviceDesc.Streams[0], "/fabex.Fabex/Get", opts...)
	if err != nil {
		return nil, err
	}
	x := &fabexGetClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Fabex_GetClient interface {
	Recv() (*Entry, error)
	grpc.ClientStream
}

type fabexGetClient struct {
	grpc.ClientStream
}

func (x *fabexGetClient) Recv() (*Entry, error) {
	m := new(Entry)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *fabexClient) GetRange(ctx context.Context, in *RequestRange, opts ...grpc.CallOption) (Fabex_GetRangeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Fabex_serviceDesc.Streams[1], "/fabex.Fabex/GetRange", opts...)
	if err != nil {
		return nil, err
	}
	x := &fabexGetRangeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Fabex_GetRangeClient interface {
	Recv() (*Entry, error)
	grpc.ClientStream
}

type fabexGetRangeClient struct {
	grpc.ClientStream
}

func (x *fabexGetRangeClient) Recv() (*Entry, error) {
	m := new(Entry)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// FabexServer is the server API for Fabex service.
type FabexServer interface {
	Get(*Entry, Fabex_GetServer) error
	GetRange(*RequestRange, Fabex_GetRangeServer) error
}

// UnimplementedFabexServer can be embedded to have forward compatible implementations.
type UnimplementedFabexServer struct {
}

func (*UnimplementedFabexServer) Get(req *Entry, srv Fabex_GetServer) error {
	return status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedFabexServer) GetRange(req *RequestRange, srv Fabex_GetRangeServer) error {
	return status.Errorf(codes.Unimplemented, "method GetRange not implemented")
}

func RegisterFabexServer(s *grpc.Server, srv FabexServer) {
	s.RegisterService(&_Fabex_serviceDesc, srv)
}

func _Fabex_Get_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Entry)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FabexServer).Get(m, &fabexGetServer{stream})
}

type Fabex_GetServer interface {
	Send(*Entry) error
	grpc.ServerStream
}

type fabexGetServer struct {
	grpc.ServerStream
}

func (x *fabexGetServer) Send(m *Entry) error {
	return x.ServerStream.SendMsg(m)
}

func _Fabex_GetRange_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RequestRange)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FabexServer).GetRange(m, &fabexGetRangeServer{stream})
}

type Fabex_GetRangeServer interface {
	Send(*Entry) error
	grpc.ServerStream
}

type fabexGetRangeServer struct {
	grpc.ServerStream
}

func (x *fabexGetRangeServer) Send(m *Entry) error {
	return x.ServerStream.SendMsg(m)
}

var _Fabex_serviceDesc = grpc.ServiceDesc{
	ServiceName: "fabex.Fabex",
	HandlerType: (*FabexServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Get",
			Handler:       _Fabex_Get_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetRange",
			Handler:       _Fabex_GetRange_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "fabex.proto",
}
