Fabric:
  user: User1
  secret:
  org: Org1
  channel:
  connectionProfile:

cassandra:
  host: localhost
  dbuser: cassandra
  dbsecret: cassandra
  keyspace: blocks
  columnfamily: txs

mongo:
  host: localhost
  port: 27018
  dbuser: mongo
  dbsecret: mongo
  dbname: blocks
  collection: txs

GRPCServer:
  host: localhost
  port: 6000

UI:
  port: 5252