name: "wheelsets-network"
#
# Schema version of the content. Used by the SDK to apply the corresponding parsing rules.
#
version: 1.0.0

#
# The client section used by GO SDK.
#
client:

  # Which organization does this application instance belong to? The value must be the name of an org
  # defined under "organizations"
  organization: RZD

  logging:
    level: info
    # Global configuration for peer, event service and orderer timeouts
    # if this this section is omitted, then default values will be used (same values as below)
    peer:
      timeout:
        connection: 600s
        response: 600s
    #      discovery:
    #        # Expiry period for discovery service greylist filter
    #        # The channel client will greylist peers that are found to be offline
    #        # to prevent re-selecting them in subsequent retries.
    #        # This interval will define how long a peer is greylisted
    #        greylistExpiry: 10s
    #  eventService:
    #    # Event service type (optional). If not specified then the type is automatically
    #    # determined from channel capabilities.
    #    type: (deliver|eventhub)
    # the below timeouts are commented out to use the default values that are found in
    # "pkg/fab/endpointconfig.go"
    # the client is free to override the default values by uncommenting and resetting
    #    # the values as they see fit in their config file
    #      timeout:
    #        connection: 15s
    #        registrationResponse: 15s
    orderer:
      timeout:
        connection: 600s
        response: 600s
    global:
      timeout:
        query: 600s
        execute: 600s
        resmgmt: 600s
  #    cache:
  #      connectionIdle: 30s
  #      eventServiceIdle: 2m
  #      channelConfig: 30m
  #      channelMembership: 30s
  #      discovery: 10s
  #      selection: 10m

  # Root of the MSP directories with keys and certs.
  cryptoconfig:
    path: ${HOME}/wheelsets-fabric/fixtures/docker-dev-2orgs/crypto-config

  # Some SDKs support pluggable KV stores, the properties under "credentialStore"
  # are implementation specific
  credentialStore:
    path: /tmp/wheelsets-store

    # [Optional]. Specific to the CryptoSuite implementation used by GO SDK. Software-based implementations
    # requiring a key store. PKCS#11 based implementations does not.
    cryptoStore:
      path: /tmp/wheelsets-msp

    # BCCSP config for the client. Used by GO SDK.
  BCCSP:
    security:
      enabled: true
      default:
        provider: "SW"
      hashAlgorithm: "SHA2"
      softVerify: true
      level: 256

  tlsCerts:
    # [Optional]. Use system certificate pool when connecting to peers, orderers (for negotiating TLS) Default: false
    systemCertPool: false

    # [Optional]. Client key and cert for TLS handshake with peers and orderers
    client:
      keyfile:
      certfile:

#
# [Optional]. But most apps would have this section so that channel objects can be constructed
# based on the content below. If an app is creating channels, then it likely will not need this
# section.
#
channels:
  # name of the channel
  wheelsets:
    # Required. list of orderers designated by the application to use for transactions on this
    # channel. This list can be a result of access control ("rzd" can only access "ordererA"), or
    # operational decisions to share loads from applications among the orderers.  The values must
    # be "names" of orgs defined under "organizations/peers"
    # deprecated: not recommended, to override any orderer configuration items, entity matchers should be used.
    # orderers:
    #  - orderer.example.com

    # Required. list of peers from participating orgs
    peers:
      peer0.rzd.wheelsets.ru:
        # [Optional]. will this peer be sent transaction proposals for endorsement? The peer must
        # have the chaincode installed. The app can also use this property to decide which peers
        # to send the chaincode install request. Default: true
        endorsingPeer: true

        # [Optional]. will this peer be sent query proposals? The peer must have the chaincode
        # installed. The app can also use this property to decide which peers to send the
        # chaincode install request. Default: true
        chaincodeQuery: true

        # [Optional]. will this peer be sent query proposals that do not require chaincodes, like
        # queryBlock(), queryTransaction(), etc. Default: true
        ledgerQuery: true

        # [Optional]. will this peer be the target of the SDK's listener registration? All peers can
        # produce events but the app typically only needs to connect to one to listen to events.
        # Default: true
        eventSource: true

      peer0.vrk1.wheelsets.ru:

    policies:
      #[Optional] options for retrieving channel configuration blocks
      queryChannelConfig:
        #[Optional] min number of success responses (from targets/peers)
        minResponses: 1
        #[Optional] channel config will be retrieved for these number of random targets
        maxTargets: 1
        #[Optional] retry options for query config block
        retryOpts:
          #[Optional] number of retry attempts
          attempts: 5
          #[Optional] the back off interval for the first retry attempt
          initialBackoff: 500ms
          #[Optional] the maximum back off interval for any retry attempt
          maxBackoff: 5s
          #[Optional] he factor by which the initial back off period is exponentially incremented
          backoffFactor: 2.0


#
# list of participating organizations in this network
#
organizations:
  rzd:
    mspid: RZDMSP
    cryptoPath: peerOrganizations/rzd.wheelsets.ru/users/{userName}@rzd.wheelsets.ru/msp
    peers:
      - peer0.rzd.wheelsets.ru

    # [Optional]. Certificate Authorities issue certificates for identification purposes in a Fabric based
    # network. Typically certificates provisioning is done in a separate process outside of the
    # runtime network. Fabric-CA is a special certificate authority that provides a REST APIs for
    # dynamic certificate management (enroll, revoke, re-enroll). The following section is only for
    # Fabric-CA servers.
    certificateAuthorities:
      - ca.rzd.wheelsets.ru

  vrk1:
    mspid: VRK1MSP
    cryptoPath: peerOrganizations/vrk1.wheelsets.ru/users/{userName}@vrk1.wheelsets.ru/msp
    peers:
      - peer0.vrk1.wheelsets.ru
    # [Optional]. Certificate Authorities issue certificates for identification purposes in a Fabric based
    # network. Typically certificates provisioning is done in a separate process outside of the
    # runtime network. Fabric-CA is a special certificate authority that provides a REST APIs for
    # dynamic certificate management (enroll, revoke, re-enroll). The following section is only for
    # Fabric-CA servers.
    certificateAuthorities:
      - ca.vrk1.wheelsets.ru

# List of orderers to send transaction and channel create/update requests to. For the time
# being only one orderer is needed. If more than one is defined, which one get used by the
# SDK is implementation specific. Consult each SDK's documentation for its handling of orderers.
#
orderers:
  orderer.wheelsets.ru:
    url: orderer.wheelsets.ru:7050

    # these are standard properties defined by the gRPC library
    # they will be passed in as-is to gRPC client constructor
    grpcOptions:
      ssl-target-name-override: orderer.wheelsets.ru
      # These parameters should be set in coordination with the keepalive policy on the server,
      # as incompatible settings can result in closing of connection.
      # When duration of the 'keep-alive-time' is set to 0 or less the keep alive client parameters are disabled
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      # allow-insecure will be taken into consideration if address has no protocol defined, if true then grpc or else grpcs
      allow-insecure: false

    tlsCACerts:
      # Certificate location absolute path
      path: ${GOPATH}/src/gitlab.sch.ocrv.com.rzd/wheelsets-fabric/fixtures/docker-dev-2orgs/crypto-config/ordererOrganizations/wheelsets.ru/tlsca/tlsca.wheelsets.ru-cert.pem
#
# List of peers to send various requests to, including endorsement, query
# and event listener registration.
#
peers:
  peer0.rzd.wheelsets.ru:
    # this URL is used to send endorsement and query requests
    url: peer0.rzd.wheelsets.ru:7051
    # eventUrl is only needed when using eventhub (default is delivery service)
    eventUrl: localhost:7053

    grpcOptions:
      ssl-target-name-override: peer0.rzd.wheelsets.ru
      # These parameters should be set in coordination with the keepalive policy on the server,
      # as incompatible settings can result in closing of connection.
      # When duration of the 'keep-alive-time' is set to 0 or less the keep alive client parameters are disabled
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      # allow-insecure will be taken into consideration if address has no protocol defined, if true then grpc or else grpcs
      allow-insecure: false

    tlsCACerts:
      # Certificate location absolute path
      path: ${GOPATH}/src/gitlab.sch.ocrv.com.rzd/wheelsets-fabric/fixtures/docker-dev-2orgs/crypto-config/peerOrganizations/rzd.wheelsets.ru/tlsca/tlsca.rzd.wheelsets.ru-cert.pem

  peer0.vrk1.wheelsets.ru:
    # this URL is used to send endorsement and query requests
    url: peer0.vrk1.wheelsets.ru:8051
    # eventUrl is only needed when using eventhub (default is delivery service)
    eventUrl: localhost:8053

    grpcOptions:
      ssl-target-name-override: peer0.vrk1.wheelsets.ru
      # These parameters should be set in coordination with the keepalive policy on the server,
      # as incompatible settings can result in closing of connection.
      # When duration of the 'keep-alive-time' is set to 0 or less the keep alive client parameters are disabled
      keep-alive-time: 300s
      keep-alive-timeout: 300s
      keep-alive-permit: false
      fail-fast: false
      # allow-insecure will be taken into consideration if address has no protocol defined, if true then grpc or else grpcs
      allow-insecure: false

    tlsCACerts:
      # Certificate location absolute path
      path: ${GOPATH}/src/gitlab.sch.ocrv.com.rzd/wheelsets-fabric/fixtures/docker-dev-2orgs/crypto-config/peerOrganizations/vrk1.wheelsets.ru/tlsca/tlsca.vrk1.wheelsets.ru-cert.pem

#
# Fabric-CA is a special kind of Certificate Authority provided by Hyperledger Fabric which allows
# certificate management to be done via REST APIs. Application may choose to use a standard
# Certificate Authority instead of Fabric-CA, in which case this section would not be specified.
#
certificateAuthorities:
  ca.rzd.wheelsets.ru:
    url: https://tlsca.rzd.wheelsets.ru:7054
    # Fabric-CA supports dynamic user enrollment via REST APIs. A "root" user, a.k.a registrar, is
    # needed to enroll and invoke new users.
    httpOptions:
      verify: false
    registrar:
      enrollId: admin
      enrollSecret: adminpw
    # [Optional] The optional name of the CA.
    caName: ca.rzd.wheelsets.ru
    tlsCACerts:
      # Certificate location absolute path
      path: ${GOPATH}/src/gitlab.sch.ocrv.com.rzd/wheelsets-fabric/fixtures/docker-dev-2orgs/crypto-config/peerOrganizations/rzd.wheelsets.ru/tlsca/tlsca.rzd.wheelsets.ru-cert.pem

  ca.vrk1.wheelsets.ru:
    url: https://tlsca.vrk1.wheelsets.ru:8054
    # Fabric-CA supports dynamic user enrollment via REST APIs. A "root" user, a.k.a registrar, is
    # needed to enroll and invoke new users.
    httpOptions:
      verify: false
    registrar:
      enrollId: admin
      enrollSecret: adminpw
    # [Optional] The optional name of the CA.
    caName: ca.vrk1.wheelsets.ru
    tlsCACerts:
      # Certificate location absolute path
      path: ${GOPATH}/src/gitlab.sch.ocrv.com.rzd/wheelsets-fabric/fixtures/docker-dev-2orgs/crypto-config/peerOrganizations/vrk1.wheelsets.ru/tlsca/tlsca.vrk1.wheelsets.ru-cert.pem

entityMatchers:
  peer:
    - pattern: (\w*)peer0.rzd.wheelsets.ru(\w*)
      urlSubstitutionExp: peer0.rzd.wheelsets.ru:7051
      eventUrlSubstitutionExp: localhost:7053
      sslTargetOverrideUrlSubstitutionExp: peer0.rzd.wheelsets.ru
      mappedHost: peer0.rzd.wheelsets.ru

    - pattern: (\w*)peer0.vrk1.wheelsets.ru(\w*)
      urlSubstitutionExp: peer0.vrk1.wheelsets.ru:8051
      eventUrlSubstitutionExp: localhost:8053
      sslTargetOverrideUrlSubstitutionExp: peer0.vrk1.wheelsets.ru
      mappedHost: peer0.vrk1.wheelsets.ru

  orderer:
    - pattern: (\w*)orderer.wheelsets.ru(\w*)
      urlSubstitutionExp: orderer.wheelsets.ru:7050
      sslTargetOverrideUrlSubstitutionExp: orderer.wheelsets.ru
      mappedHost: orderer.wheelsets.ru

  certificateAuthorities:
    - pattern: (\w*)ca.rzd.wheelsets.ru(\w*)
      urlSubstitutionExp: https://tlsca.rzd.wheelsets.ru:7054
      sslTargetOverrideUrlSubstitutionExp: ca.rzd.wheelsets.ru
      mappedHost: ca.rzd.wheelsets.ru

    - pattern: (\w*)ca.vrk1.wheelsets.ru(\w*)
      urlSubstitutionExp: https://tlsca.vrk1.wheelsets.ru:8054
      sslTargetOverrideUrlSubstitutionExp: ca.vrk1.wheelsets.ru
      mappedHost: ca.vrk1.wheelsets.ru
