Fabric:
  user: admin
  secret: adminpw
  org: rzd
  channel: wheelsets
  connectionProfile: /app/config-dev-2orgs.yaml

Db:
  host: localhost
  port: 27017
  dbuser: admin
  dbsecret: adminpw
  dbname: blocks
  collection: txs

GRPCServer:
  host: localhost
  port: 6000
