Fabric:
  user: Admin
  secret: adminpw
  org: Org1
  channel: mychannel
  connectionProfile: /app/configs/connection-profile.yaml

cassandra:
  host: cassandra
  dbuser: cassandra
  dbsecret: cassandra
  keyspace: blocks
  columnfamily: txs

mongo:
  host: localhost
  port: 27018
  dbuser: mongo
  dbsecret: mongo
  dbname: blocks
  collection: txs

GRPCServer:
  host: localhost
  port: 6000

UI:
  port: 5252