Fabric:
  user: admin
  secret: adminpw
  org: rzd
  channel: wheelsets
  connectionProfile: /app/config-dev-2orgs.yaml

cassandra:
  host: localhost
  dbuser: cassandra
  dbsecret: cassandra
  keyspace: blocks
  columnfamily: txs

mongo:
  host: localhost
  port: 27018
  dbuser: mongo
  dbsecret: mongo
  dbname: blocks
  collection: txs

GRPCServer:
  host: localhost
  port: 6000
