---
name: test-network-org1
version: 1.0.0
client:
  organization: Org1
  connection:
    timeout:
      peer:
        endorser: '300'

  cryptoconfig:
    path: /crypto


    # BCCSP config for the client. Used by GO SDK.
  BCCSP:
    security:
      enabled: true
      default:
        provider: "SW"
      hashAlgorithm: "SHA2"
      softVerify: true
      level: 256

  tlsCerts:
    # [Optional]. Use system certificate pool when connecting to peers, orderers (for negotiating TLS) Default: false
    systemCertPool: false

    # [Optional]. Client key and cert for TLS handshake with peers and orderers
    client:
      keyfile:
      certfile:

organizations:
  Org1:
    mspid: Org1MSP
    cryptoPath: peerOrganizations/peerOrganizations/org1.example.com/users/{username}@org1.example.com/msp/
    peers:
      - peer0.org1.example.com
    certificateAuthorities:
      - ca.org1.example.com
peers:
  peer0.org1.example.com:
    url: grpcs://0.0.0.0:7051
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICJjCCAc2gAwIBAgIUCRialDuqW4ucJukeDWIg9Cm9gHEwCgYIKoZIzj0EAwIw
        cDELMAkGA1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMQ8wDQYDVQQH
        EwZEdXJoYW0xGTAXBgNVBAoTEG9yZzEuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2Nh
        Lm9yZzEuZXhhbXBsZS5jb20wHhcNMjEwMTI3MDg1NzAwWhcNMzYwMTI0MDg1NzAw
        WjBwMQswCQYDVQQGEwJVUzEXMBUGA1UECBMOTm9ydGggQ2Fyb2xpbmExDzANBgNV
        BAcTBkR1cmhhbTEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEcMBoGA1UEAxMT
        Y2Eub3JnMS5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABPY5
        yWqYaqifvWa3+9RyeZXToVEz5fEMCUaGr1g9z1ry0cgCjG2Z8hr02NcYSIr4iX4a
        Fm1gJw4Oq6zB8/I/+lSjRTBDMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAG
        AQH/AgEBMB0GA1UdDgQWBBRIi0OR28Rxdf40/1eTQxuX+dV1tTAKBggqhkjOPQQD
        AgNHADBEAiBShIIHhuxS2eg8UMmKNSarpVR7/awBvvjQljP+encuSgIgAqfT9L57
        M3h8GKQGoS5/Qjj+TS2KPLXgiw47oTGDwFw=
        -----END CERTIFICATE-----

    grpcOptions:
      ssl-target-name-override: peer0.org1.example.com
      hostnameOverride: peer0.org1.example.com
certificateAuthorities:
  ca.org1.example.com:
    url: https://org1.example.com:7054
    caName: ca-org1
    tlsCACerts:
      pem:
        - |
          -----BEGIN CERTIFICATE-----
          MIICJjCCAc2gAwIBAgIUCRialDuqW4ucJukeDWIg9Cm9gHEwCgYIKoZIzj0EAwIw
          cDELMAkGA1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMQ8wDQYDVQQH
          EwZEdXJoYW0xGTAXBgNVBAoTEG9yZzEuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2Nh
          Lm9yZzEuZXhhbXBsZS5jb20wHhcNMjEwMTI3MDg1NzAwWhcNMzYwMTI0MDg1NzAw
          WjBwMQswCQYDVQQGEwJVUzEXMBUGA1UECBMOTm9ydGggQ2Fyb2xpbmExDzANBgNV
          BAcTBkR1cmhhbTEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEcMBoGA1UEAxMT
          Y2Eub3JnMS5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABPY5
          yWqYaqifvWa3+9RyeZXToVEz5fEMCUaGr1g9z1ry0cgCjG2Z8hr02NcYSIr4iX4a
          Fm1gJw4Oq6zB8/I/+lSjRTBDMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAG
          AQH/AgEBMB0GA1UdDgQWBBRIi0OR28Rxdf40/1eTQxuX+dV1tTAKBggqhkjOPQQD
          AgNHADBEAiBShIIHhuxS2eg8UMmKNSarpVR7/awBvvjQljP+encuSgIgAqfT9L57
          M3h8GKQGoS5/Qjj+TS2KPLXgiw47oTGDwFw=
          -----END CERTIFICATE-----

    httpOptions:
      verify: false

entityMatchers:
  certificateAuthorities:
    - pattern: (\w*)org1.example.com(\w*)
      urlSubstitutionExp: https://tlsca.org1.example.com:7054
      sslTargetOverrideUrlSubstitutionExp: org1.example.com
      mappedHost: org1.example.com
