name: unit-tests

on:
  push:
    branches: [ master, 1.x, 2.x ]
  pull_request:
    branches: [ master, 1.x, 2.x ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: setup env
      run: |
        echo "GO111MODULE=on" >> $GITHUB_ENV

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: extract dependencies
      run: tar -xvf vendor.tar

    - name: unit tests
      run: cd blockhandler && go test
